### ISSUE TITLE
PHP Fatal Error: Call to a member function fetch_assoc() on a non-object in class.JobberSettings.php on line 23

### ISSUE THREAD

**Issue by netfirm** [jrschumacher/jobberbase#1]
Hi, I'm experiencing a PHP Error in class.JobberSettings.php on line 23 with the function fetch_assoc()
Could you please help? I have pasted the file below.
-------------------------------------------------------------------------------------------------------------------------------
<?php
/**
 * jobberbase site configuration class
 *
 * @author     Erik Goverde  <http://chronoscripts.com> <chronos@chronoscripts.com>
 * @license    You are free to edit and use this work, but please keep the credits.
 * 
 */

class JobberSettings
{
	var $mSettings = false;
		
	public function __construct()
	{
		global $db;
		
		$sql = 'SELECT * FROM '.DB_PREFIX.'settings ORDER BY id ASC';
		$result = $db->query($sql);
		
		$settings = array();
		
		while ($row = $result->fetch_assoc())
		{
			// Setting temporary variable names for the 'value' and 'fieldtype' fields
			$value = $row['value']; 
			$data_type = $row['data_type'];
			$input_type = $row['input_type'];
			$input_options = $row['input_options'];
			$validation = explode('|', $row['validation']); 
				
			// Apply certain actions on special fields 
			if ($input_type == 'checkbox' || $input_type == 'select' || $input_type == 'radiobutton')
			{
				$input_options = explode('|', $input_options);
			}
			else if ($input_type == 'available_themes')
			{
				$input_type = 'select';	
				$themes = array();
				$dir = APP_PATH.'_tpl/';
				if ($dh = opendir($dir)) {
				    while (($file = readdir($dh)) !== false) { if (filetype($dir . $file) != 'file' && $file != '.' && $file != '..' && $file != '.svn' && $file != '_cache') $themes[] = $file; }
					closedir($dh);
				}
				$input_options = $themes;
			}
			else if ($input_type == 'available_pages')
			{
				$input_type = 'select';
				$pages = array('');
				$sql = '
					SELECT url 
					FROM '.DB_PREFIX.'pages 
					ORDER BY url ASC';
				if ($resultPages = $db->query($sql))
				{
					while ($resultRow = $resultPages->fetch_assoc())
					{
						$pages[] = $resultRow['url'];
					}
				}
				$input_options = $pages;
			}
			else if ($input_type == 'timezones')
			{
				$input_type = 'select';	
				$timezones = array();
				
				$timezones = timezone_identifiers_list();
				
				$input_options = $timezones;
			}
			
			
			if ($data_type == 'boolean' && $value != 1) 
			{
				$value = false;
			}
				
			// Add the row to the setting array
			$settings[$row['name']] = array(
				'name' => $row['name'], 
				'title' => $row['title'], 
				'description' => $row['description'],
				'data_type' => $data_type,
				'input_type' => $input_type,
				'input_options' => $input_options,
				'validation' => $validation,
				'value' => stripslashes($value), 
				'category_id' => $row['category_id'],
				'extradata' => $row['extradata']
			);
		}
		
		$this->mSettings = $settings;

	}
	
	public function GetSettingsCategories()
	{
	    global $db;
	    $sql = 'SELECT id, name, var_name, description  
				FROM '.DB_PREFIX.'settings_categories 
				ORDER BY id ASC';
	    $result = $db->query($sql);
	    
	    $settings_category = array();
		
		while ($row = $result->fetch_assoc())
		{
			$settings_category[] = array('name' => $row['name'], 'var_name' => $row['var_name'], 'description' => $row['description']);
		}
		return $settings_category;
	}

	public function GetSettingsCategoryNameById($id)
	{
		global $db;
	    $sql = 'SELECT name 
				FROM '.DB_PREFIX.'settings_categories 
				WHERE id = ' . $id;
	    $result = $db->query($sql);
	    $row = $result->fetch_assoc();
		return $row['name'];
	}
	
	public function GetSettingsCategoryIdByVarname($var_name)
	{
		global $db;
	    $sql = 'SELECT id 
				FROM '.DB_PREFIX.'settings_categories 
				WHERE var_name = "' . $var_name . '"';
	    $result = $db->query($sql);
	    $row = $result->fetch_assoc();
		return $row['id'];
	}

	public function GetSetting($name, $advanced = false)
	{
		$settings = $this->mSettings;
		if (!empty($settings[$name]))
		{
			if ($advanced == true) return $settings[$name];
			else return $settings[$name]['value'];
		}
		else
			return false;
	}
	
	public function GetSettings($setting_names = false, $advanced = false)
	{
		$settings = $this->mSettings;
		$settings_array = array();
		
		if (!empty($setting_names))
		{
			$count = count($setting_names);
			$i = 0; 
			while($i < $count)
			{
				if (!empty($settings[$setting_names[$i]]) && $advanced == true)
				{
					$settings_array[$setting_names[$i]] = $settings[$setting_names[$i]];
				}
				elseif (!empty($settings[$setting_names[$i]]))
				{
					$settings_array[$setting_names[$i]] = $settings[$setting_names[$i]]['value'];
				}
					
				$i++;
			}
			return $settings_array;
		}
		elseif ($advanced === false)
		{
			foreach ($settings as $setting)
			{
				$settings_array[$setting['name']] = (!empty($setting['extradata']) && $setting['name'] == 'site_logo') ? $setting['extradata'] : $setting['value'];
			}

			return $settings_array;
		}
		else 
		{
			return $settings;
		}
	}
	
	public function GetSettingsByCategory($category_id, $advanced = false)
	{
		global $db;
		$sql = 'SELECT name
				FROM '.DB_PREFIX.'settings
				WHERE category_id = ' . $category_id . ' ORDER BY ordering ASC';
		$result = $db->query($sql);
		
		$settings_list = array();
		
		while ($row = $result->fetch_assoc()) {	$settings_list[] = $row['name']; }

		$settings = $this->GetSettings($settings_list, $advanced);

		return $settings;
	}

	public function UpdateSettings($settings_array)
	{
		global $db, $cache;
		
		// remove cache
        $cache->removeCache(CACHE_SITE_SETTINGS);
		
		$settings = $this->mSettings; $i = 0;
		$count = count($settings_array);
		
		while($i < $count)
		{
			$value = $settings_array[$i]['value'];
			$name = $settings_array[$i]['name'];
			$extradata = $settings_array[$i]['extradata'];
			$extradata_q = '';
			
			if (!empty($extradata))
			{
				$extradata_q = ', extradata = "' . $extradata . '"';
			}
			
			
			if ($value != $settings[$name]['value'] || !empty($extradata_q))
			{
				$sql = 'UPDATE '.DB_PREFIX.'settings SET value = "' . $value . '"' . $extradata_q . ' WHERE name = "' . $name . '"';
				$extradata = '';
				$extradata_q = null;
				$db->query($sql);
			}
			
			$i++;
		}
	}
}
?>

**Comment by jrschumacher** [comment]
You should use: https://github.com/filipcte/jobberbase

**Comment by netfirm** [comment]
Too late! Last email to Filipe directly was on 08/07/15. Our IT Dept advised that all the issues experienced with Jobberbase was not on our server-end. Even forwarded on the email from IT. Filipe hasn't even bothered responding! Shocking response time and support. Jobberbase UNINSTALLED!


    Tiffany Liow
    E  webmaster@netfirm.net.au
    www.netfirm.net.au
    Latest Jobs, Best Talent!


On 30 Jul 2015, at 11:19 PM, Ryan Schumacher <notifications@github.com> wrote:

You should use: https://github.com/filipcte/jobberbase

**Comment by netfirm** [comment]
Too late! Last email to Filipe directly was on 08/07/15. Our IT Dept advised that all the issues experienced with Jobberbase was not on our server-end. Even forwarded on the email from IT. Filipe hasn't even bothered responding! Shocking response time and support. Jobberbase UNINSTALLED!


    Tiffany Liow
    E  webmaster@netfirm.net.au
    www.netfirm.net.au
    Latest Jobs, Best Talent!


On 30 Jul 2015, at 11:19 PM, Ryan Schumacher <notifications@github.com> wrote:

Closed #1.

**Comment by jrschumacher** [comment]
Not sure why you are so riled up. You do realize it was free software?

**Comment by netfirm** [comment]
and that warrants poor customer service? 
but far from riled up. 


    Tiffany Liow
    E  webmaster@netfirm.net.au
    

On 31 Jul 2015, at 2:04 PM, Ryan Schumacher <notifications@github.com> wrote:

Not sure why you are so riled up. You do realize it was free software?

**Comment by jrschumacher** [comment]
Customer service is for customers. You are not a customer unless you have
purchased a license to the software. This is why SLAs exist.

Let's say you read an intriguing blog post about some idea or theory. Now
let's say you've seen its been 6 years since the author last edited it. As
you are reading you find grammatical and theoretical issues with it. You
also see that there are major flaws in the article because what worked then
isn't working now. Do you email the author and demand her to edit the blog
article to reflect theoretical changes? Do you consider it poor customer
service because she hadn't responded or taken it as priority in comparison
to her current practice or employment?

For your success you really need to understand how OSS works and how you
can utilize it. If you need timely responses then look for software that
offers the purchase of an SLA. Also there are lots of free coding classes
online so you can empower yourself to fix the issues.

Peace,
Ryan

**Comment by netfirm** [comment]
Thanks Ryan, you've given me more than Filipe has over 6 emails.

Cheers

    Tiffany Liow
    E  webmaster@netfirm.net.au
    www.netfirm.net.au
    Latest Jobs, Best Talent!


On 31 Jul 2015, at 8:43 PM, Ryan Schumacher <notifications@github.com> wrote:

Customer service is for customers. You are not a customer unless you have
purchased a license to the software. This is why SLAs exist.

Let's say you read an intriguing blog post about some idea or theory. Now
let's say you've seen its been 6 years since the author last edited it. As
you are reading you find grammatical and theoretical issues with it. You
also see that there are major flaws in the article because what worked then
isn't working now. Do you email the author and demand her to edit the blog
article to reflect theoretical changes? Do you consider it poor customer
service because she hadn't responded or taken it as priority in comparison
to her current practice or employment?

For your success you really need to understand how OSS works and how you
can utilize it. If you need timely responses then look for software that
offers the purchase of an SLA. Also there are lots of free coding classes
online so you can empower yourself to fix the issues.

Peace,
Ryan

**Comment by jrschumacher** [comment]
You might want to look at http://wpjobboard.net/. It has the kind of
support plans you are looking for.

**Comment by netfirm** [comment]
Thanks Ryan , have already purchased WP Jobmonster (noo themes) and WPJobus ... Only because Filipe wasted a month of our projected Site setup time ... Am customising now 


    Tiffany Liow
    E  webmaster@netfirm.net.au
    www.netfirm.net.au
    Latest Jobs, Best Talent!


On 31 Jul 2015, at 11:57 PM, Ryan Schumacher <notifications@github.com> wrote:

You might want to look at http://wpjobboard.net/. It has the kind of
support plans you are looking for.
